//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cửa hàng bị trùng. Vui lòng nhập lại.
        /// </summary>
        public static string ErrorMsg_DuplicateCode {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMT đã bị trùng. Vui lòng nhập lại.
        /// </summary>
        public static string ErrorMsg_DuplicateIndentify {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicateIndentify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sđt đã bị trùng. Vui lòng nhập lại.
        /// </summary>
        public static string ErrorMsg_DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("ErrorMsg_DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ không được để trống.
        /// </summary>
        public static string ErrorMsg_EmptyAddress {
            get {
                return ResourceManager.GetString("ErrorMsg_EmptyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cửa hàng không được để trống.
        /// </summary>
        public static string ErrorMsg_EmptyCode {
            get {
                return ResourceManager.GetString("ErrorMsg_EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được để trống. Vui lòng nhập Email.
        /// </summary>
        public static string ErrorMsg_EmptyEmail {
            get {
                return ResourceManager.GetString("ErrorMsg_EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống. Vui lòng nhập tên.
        /// </summary>
        public static string ErrorMsg_EmptyFullName {
            get {
                return ResourceManager.GetString("ErrorMsg_EmptyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng không tồn tại. Vui lòng nhập lại.
        /// </summary>
        public static string ErrorMsg_EmptyId {
            get {
                return ResourceManager.GetString("ErrorMsg_EmptyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMT không được để trống. Vui lòng nhập CMT.
        /// </summary>
        public static string ErrorMsg_EmptyIndentifyNumber {
            get {
                return ResourceManager.GetString("ErrorMsg_EmptyIndentifyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sđt không được để trống. Vui lòng nhập Sđt.
        /// </summary>
        public static string ErrorMsg_EmptyPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorMsg_EmptyPhoneNumber", resourceCulture);
            }
        }
    }
}
